php artisan make:model Brand
php artisan make:model Category
php artisan make:model Product
php artisan make:model Attribute
php artisan make:model AttributeValue
php artisan make:model ProductVariant
php artisan make:model ProductImage
php artisan make:model ProductSpecification
php artisan make:model Order
php artisan make:model OrderItem
php artisan make:model Review
php artisan make:model CartItem
php artisan make:model StockMovement
